# LGN, TLC {#tlc}


## Ley de los Grandes Número (LGN)

Sea $X_1, X_2, X_3,...$ i.i.d. con media $\mu$. La $\textbf{media muestral}$ es 
$\bar X_n=\frac{X_1+X_2+X_3+...+X_n}{n}$
La $\textbf{Ley de los Grandes Números}$ dice que cuando $n \rightarrow \infty$, $\bar X_n \rightarrow \mu$ con probabilidad 1. Por ejemplo, al tirar una moneda con probabilidad $p$ de cara, sea $X_j$ el indicador del $j-ésimo$ intento que es cara. La LGN dice que la proporción de Caras converge a $p$ (con probabilidad 1).

## Teorema del Límite Central (TLC)

$\textbf{Aproximando con el TLC}$
Utilizamos $\dot \sim$ para denotar que es $aproximadamente distribuido$. Podemos usar el $\textbf{Teorema del Límite Central}$ para aproximar la distribución de una variable aleatoria $Y=X_ + X_2 + ... + X_n$ que es la suma de $n$ i.i.d. variables aleatorias $X_i$. Sea $E(Y)= \mu_Y$ y $Var(Y)=\sigma ^2 _y$. El TLC dice que
$Y \sim N(\mu_y, \sigma^2 _y)$

Si las $X_i$ son i.i.d. con media $\mu_X$ y varianza $\sigma^2 _X$, entonces $\mu_Y=n\mu_X$ y $\sigma^2_Y=n\sigma^2_X$. Para la media muestral $\bar X_n$, el TLC dice
$\bar X_n = \frac{1}{n}(X_1+X_2+...+X_n)\sim N(\mu_X, \sigma^2_x/n)$

$\textbf{Distribuciones sintóticas utilizando el TLC}$

Usamos $\xrightarrow{\;\; D \;\; }$ para denotar que $\textit{converge en distribución a}$ conforme $n \rightarrow \infty$. El TLC dice que si estandarizamos la suma $X_1+X_2+...+X_n$ entonces la distribución de la suma converge a $N(0,1)$ conforme $n \rightarrow \infty$:
$\frac{1}{\sigma \sqrt{y}}(X_1+...+X_n-n\mu_X)\xrightarrow{\;\; D \;\; } N(0,1)$
