# Tabla de Distribuciones {#dist}

| Distribución   |   PMF/PDF y Dominio    |   Valor Esperado  | Varianza  | FGM |
|----------------|------------------------|-------------------|-----------|-----|
| Bernoulli. $Bern(p)$ | $P(X=1)=p$. $P(X=0)=q=1-p$ | $p$ | $pq$ | $q+pe^t$  |  
| Binomial. $Bin(n,p)$ | $P(X=k)= {n \choose k}p^kq^{n-k}$. $k \in$ {$0,1,2,...,n$}| $np$| $npq$| $(q+pe^t)^n$ |
| Geométrica. $Geom(p)$ | $P(X=k)=q^kp$. $k \in$ {$0,1,2,...$} |$q/p$|$q/p^2$|$\frac{p}{1-qe^t}, qe^t <1$|   
| Binomial Negativa. $NBin(r,p)$|$P(X=n)={{r+n-1} \choose {r-1}} p^rq^n$. $n \in$ {$0,1,2,...$}|$rq/p$|$rq/p^2$|$(\frac{p}{1-qe^t})^r, qe^t <1$|   
| Hipergeométrica. $HGeom(w,b,n)$ |$P(X=k)={w \choose k}{b \choose {n-k}}/{{w+b}\choose n}$|$\mu =\frac{nw}{b+w}$|$(\frac{w+b-n}{w+b-1})n\frac{\mu}{n}(1-\frac{\mu}{n})$| - |   
| Poisson. $Pois(\lambda)$ |$P(X=k)=\frac{e^{-\lambda}\lambda^k}{k!}$. $k \in$ {$0,1,2,...$}|$\lambda$| $\lambda$|$e^{\lambda (e^t-1)}$ |   
| Uniforme. $Unif(a,b)$ |$f(x)=\frac{1}{b-a}.$ $x \in (a,b)$|$\frac{a+b}{2}$|$\frac{(b-a)^2}{12}$|$\frac{e^{tb}-e^{ta}}{t(b-a)}$|   
| Normal. $N(\mu, \sigma^2)$|$f(x)=\frac{1}{\sigma\sqrt{2 \pi}}e^{-(x-\mu)^2/(2\sigma^2)}$. $x\in (-\infty, \infty)$|$\mu$|$\sigma^2$|$e^{t\mu+\frac{\sigma^2t^2}{2}}$|   
| Exponencial. $Expo(\lambda)$|$f(X)=\lambda e^{-\lambda x}$. $x\in (0,\infty)$|$\frac{1}{\lambda}$|$\frac{1}{\lambda^2}$|$\frac{\lambda}{\lambda -t}, t<\lambda$|   
| Gamma. $Gamma(\alpha,\lambda)$|$f(x)=\frac{1}{\Gamma(\alpha)}(\lambda x)^{\alpha}e^{\lambda x \frac{1}{x}}$|$\frac{\alpha}{\lambda}$|$\frac{\alpha}{\lambda^2}$|$(\frac{\lambda}{\lambda -t}^{\alpha}),t<\lambda$|   
| Beta. $Beta(a,b)$|$f(x)=\frac{\Gamma(a+b)}{\Gamma(a)\Gamma(b)}x^{a-1}(1-x)^{b-1}$. $x \in (0,1)$|$\mu=\frac{a}{a+b}$|$\frac{\mu(1-\mu)}{(a+b+1)}$|-|   
| Log-Normal. $LN(\mu, \sigma^2)$|$f(x)=\frac{1}{x\sigma\sqrt{2 \pi}}e^{-(logx-\mu)^2/(2\sigma^2)}$. $x\in (0, \infty)$|$\theta=e^{\mu + \sigma^2/2}$|$\theta^2(e^{\sigma^2}-1)$|no existe| 
| Chi-Cuadrado. $X^2_n$|$\frac{1}{2^{n/2}\Gamma(n/2)x^{n/2}e^{-x/2}}$. $x\in (0,\infty)$|$n$|$2n$|$(1-2t)^{-n/2}, t<1/2$|   
| T-Student. $t_n$|$\frac{\Gamma((n+1)/2)}{\sqrt{n \pi}\Gamma(n/2)}$. $x\in(-\infty,\infty)$|$0$si$n>1$|$\frac{n}{n-2}$ si $n>2$|no existe|   